version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ng"
    ports:
      - "5432:5432"
    networks:
      - db_network

networks:
  db_network:
